version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: instagram
      MYSQL_ROOT_PASSWORD: test1!
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always
